#WAP to demonstrate built-in functions in Lists
list1 = [1, 2, 3, 4, 5]
print(list1.__len__())
print(list1)
list1.append(6)
print(list1)
list1.insert(1, 10)
print(list1)
list1.pop(3)
print(list1)
list1.remove(5)
print(list1)
list1.reverse()
print(list1)
list1.sort()
print(list1)
list1.clear()
print(list1)
print(list1.__len__())
