ls=[1,5,7,29,30]
print("Built-in function of list are:")
print(ls)
li=len(ls)
print("length of list: ",li)
li=min(ls)
print("Minimum value in list: ",li)
li=max(ls)
print("Maximum value in list: ",li)
li=sum(ls)
print("Sum of list: ",li)
