my_list = [3, 1, 4, 1, 5, 9, 2, 6, 5]
print("Original list:", my_list)
print("Length of the list:", len(my_list))
print("Maximum value in the list:", max(my_list))
print("Minimum value in the list:", min(my_list))
print("Sum of all elements in the list:", sum(my_list))
sorted_list = sorted(my_list)
print("Sorted list:", sorted_list)
index_of_5 = my_list.index(5)
print("Index of first occurrence of 5:", index_of_5)
count_of_1 = my_list.count(1)
print("Count of occurrences of 1:", count_of_1)
my_list.append(7)
print("List after appending 7:", my_list)
popped_element = my_list.pop()
print("Popped element:", popped_element)
print("List after popping:", my_list)
my_list.extend([8, 9, 10])
print("List after extending with [8, 9, 10]:", my_list)
